### ISSUE TITLE
Player can survive a boulder when pressing ctrl  while being hit

### ISSUE THREAD

**Issue by Blumenkol** [infomediadesign/Paws_of_Memories#130]
When the player presses ctrl while the boulder passes through them, collision isn't registered and the player can survive being hit by a boulder. This should be fixed AFTER Tech Demo.

**Comment by KoMeyer** [comment]
the updateBoulder function (to update its hitbox) wasnt called constantly, but every 2 cycles. Doing that every cycle fixed the issue.

**Comment by KoMeyer** [comment]
Nvm the player sometimes survives for some reason I dont see rn

**Comment by KoMeyer** [comment]
Its if the player is moving towards a moving boulder that he survives

**Comment by KoMeyer** [comment]
Fixed. Made it so if the player and boulder collide the player dies, collision has a small window for happening (about 2pixels, which should work in all cases)
