### ISSUE TITLE
Character is too Small in comparison to current Screen resolution.

### ISSUE THREAD

**Issue by Blumenkol** [infomediadesign/Paws_of_Memories#15]
Character: 1 Tile
Tile Size: 24x24 px
Current Screen Size: 960 x 540 px

Character is 0.1% of the Screen
There are about 900 Tiles on our Screen

**Comment by Blumenkol** [comment]
Proposal is to decrease screen size and increase character scale. We need to see if increasing the chracter scale decreases the quality by a significant amount. If this works the artists *will not* have to make the charcter assets all over again.

**Comment by KoMeyer** [comment]
Player is currently 48*48 pixels, can be adjusted ad desired
