### ISSUE TITLE
Gallery implimenation

### ISSUE THREAD

**Issue by Tamina345** [infomediadesign/Paws_of_Memories#177]

**Comment by Blumenkol** [comment]
- [ ] Screen
- [ ] durchflippen
- [ ] bool für gesammelt/nicht gesammelt

**Comment by Blumenkol** [comment]
Idea: Player presses the gallery button animation of book opening OR pages flipping
if an image has been unlocked the player can see a static image of the memory, if the image hasn't been unlocked the player sees an empty polaroid.

**Comment by Blumenkol** [comment]
Need to add correct animation
