### ISSUE TITLE
setting Artstyle, pixle ratio and detail

### ISSUE THREAD

**Issue by Tamina345** [infomediadesign/Paws_of_Memories#2]
Discussion and setting of all framework conditions.

**Comment by Tamina345** [comment]
@LF-Cheeseburger, @Blumenkol, @Szabi21, @Tamina345
Charakter is one title big (as big as boulders and walls).
Tile Dimentions (Level of detail): **24x24 p**

**Comment by Tamina345** [comment]
How does the charakter move? tile by tile or with a smoth annimation?

**Comment by Blumenkol** [comment]
Smooth animation might be too much to finish until 21st of April. I think we should implement tile by tile movement for now and implement smooth animation in polishing phase (or in between) if there is time left.

**Comment by Tamina345** [comment]
Amound of colours:

- cat: 7
- fork: 5
- wall:
- boulders:
- background (game):
- background (menu): 
-
