### ISSUE TITLE
Sprite (for texture loading, updating etc.)

### ISSUE THREAD

**Issue by Tamina345** [infomediadesign/Paws_of_Memories#20]

**Comment by KoMeyer** [comment]
Aight das is unser Hauptziel diese Woche. Kann gut sein das Till sich mehr damit befasst als ich, da ich noch mit Tiled arbeite und das andere Modul ja wiederhole.

Ziel sollte sein, einr Klasse zu haben welche die Sprites aller anderen Klassen managed und eventuell updated.

Man könnte sich auch überlegen alle zusammengehörigen Animationen (z.B. Katze) in eine große PNG Datei zu tun, damit man nur eine Datei laden muss.

**Comment by KoMeyer** [comment]
Hab eine Sprite Klasse erstellt. Diese vererbt Vektor Koordinaten, einen boolean ob dieser Sprite active ist oder nicht, und eine Textur.
Das Loaden von Texturen und deren Zuweisung sollte eventuell von dem game Controller getätigt werden.
