### ISSUE TITLE
movement implimentation

### ISSUE THREAD

**Issue by Tamina345** [infomediadesign/Paws_of_Memories#4]
- [x] walking
- [x] digging
- [x] grabbing

**Comment by KoMeyer** [comment]
/*
 *  Currently all code is written in the main file. This is to convoluted and hard to keep track of.
 *  Therefore the current tasks are:
 *  <<PLAYER>>
 *  - write the movement script into the player class (includes coordinates)
 *  - add the digging function to the player class
 *  - add the grabbing function to the player class
 *      --> grab when running into it, or grabbing next to the player. Add int for memories gathered
 *  <<Dirt>>
 *  - add coordinates
 *  - add function to delete the dirt (digging)
 *  <<Memory>>
 *  - add coordinates
 *  - add function to delete the memory (if picked up)
 */
